version: '3.5'

services: 
  backend:
    build: backend/
    ports: 
      - 8000:8000
    container_name: backend
  
  frontend:
    build: frontend/
    ports: 
      - 5000:5000
    container_name: frontend