version: '3.5'

services: 
  db: 
    image: postgres
    restart: unless-stopped
    environment:
      DB_USERNAME: exam
      DB_PASSWORD: example
    container_name: db_redmine
    volumes:
      - database:/var/lib/postgresql/data

  redmine:
    image: redmine
    environment:
      - REDMINE_DB_POSTGRES=db
      - REDMINE_DB_PASSWORD=example
    ports:
      - 9999:3000
    volumes:
      - files:/usr/src/redmine/files
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DESIGN=galkaev
    ports:
      - 8083:8080

  server:
    build: .
    container_name: server
    environment:
      - REDIS=db
    ports:
      - 8000:8000

volumes:
  database:
  files: